version: "2"

run:
  tests: false
  timeout: 1m
  relative-path-mode: gomod
  concurrency: 4

linters:
  default: all
  disable:
    - depguard
    - testpackage
    - testifylint
    - varnamelen
    - noctx
    - exhaustruct
    - dupl
    - revive
    - ireturn
  exclusions:
    paths:
      - "gen/openapi/"
      - "gen/mock/"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    paths:
      - "gen/openapi/"
      - "gen/mock"
